// <auto-generated />

using System;
using Database.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Database.EFCore.Migrations
{
    [DbContext(typeof(ExampleContext))]
    partial class ExampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Database.EFCore.Entities.Car", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy",
                        NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Car");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "BMW"
                    },
                    new
                    {
                        Id = 2,
                        Name = "Audi"
                    },
                    new
                    {
                        Id = 3,
                        Name = "Mercedes"
                    }
                );
            });

            modelBuilder.Entity("Database.EFCore.Entities.CarModel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy",
                        NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int?>("CarId")
                    .HasColumnType("integer");

                b.Property<decimal>("Name")
                    .HasColumnType("string");

                b.Property<DateTime>("TypeEngine")
                    .HasColumnType("string");

                b.HasKey("Id");

                b.HasIndex("CarId");

                b.ToTable("CarModel");

                b.HasData(
                    new
                    {
                        Id = 1,
                        Name = "M5",
                        TypeEngine = "Petrol",
                        CarId = 1
                    },
                    new
                    {
                        Id = 2,
                        Name = "RS7",
                        TypeEngine = "Petrol",
                        CarId = 2
                    },
                    new
                    {
                        Id = 3,
                        Name = "E63",
                        TypeEngine = "Petrol",
                        CarId = 3
                    });
            });

            modelBuilder.Entity("Database.EFCore.Entities.CarModel", b =>
            {
                b.HasOne("Database.EFCore.Entities.Car", "Car")
                    .WithMany()
                    .HasForeignKey("CarId");
            });
#pragma warning restore 612, 618
        }
    }
}